name: build-release
on: 
  push:
    tags:
      - v*
jobs:
  build-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          buildkitd-flags: --debug

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create output dir
        run: |
          mkdir -p apk

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: android/Dockerfile
          context: .
          outputs: apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: apk/apolloui-prod-release-unsigned.apk

      - name: Upload mapping
        uses: actions/upload-artifact@v3
        with:
          name: mapping
          path: apk/mapping.txt
