name: pr
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

        with:
          buildkitd-flags: --debug

      - name: Checkout
        uses: checkout@v4

      # https://github.com/gradle/wrapper-validation-action/releases/tag/v1.0.5
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6

      - name: Create output dir
        run: |
          mkdir -p apk

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: android/Dockerfile
          context: .
          outputs: apk

      - name: Upload APK
        uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571
        with:
          name: apk
          path: apk/apolloui-prod-release-unsigned.apk
